AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  EnvironmentName:
    Type: String
    Default: Dev
  APIName:
    Type: String
    Default: ModelOrganization
  EC2Type:
    Type: String
    Description: EC2 instance type for Bastion
    Default: t2.medium
  VPC:
    Type: AWS::EC2::VPC::Id
    Default: vpc-7aec6412
  PubSubnet1:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-7709841f
  PrivSubnet1:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-f862a782
  PrivSubnet2:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-6298952f
  Subnet1:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-f862a782
  Subnet2:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-6298952f
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
    Default: sg-86fb80ed
  EC2ImageID:
    Type: String
    Default: ami-e79fac82
  ASEC2Key:
    Type: String
    Default: testing-apis
  SQLServer:
    Type: String
    Default: "100.100.100.100"
  REDISUrl:
    Type: String
    Default: "as-redis-test.9jwysu.ng.0001.use2.cache.amazonaws.com"
Conditions:
  CreateEC2ModelOrganization: !Equals [!Ref APIName, "ModelOrganization"]
  CreateEC2Provisioning: !Equals [!Ref APIName, "Provisioning"]
  CreateEC2Workspace: !Equals [!Ref APIName, "Workspace"]
  CreateEC2WorkspaceReports: !Equals [!Ref APIName, "WorkspaceReports"]
Resources:
  ASAPIModelOrg:
    Type: AWS::EC2::Instance
    Condition: CreateEC2ModelOrganization
    Properties:
      ImageId: !Ref EC2ImageID
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref MySecurityGroup
      SubnetId: !Ref PrivSubnet2
      IamInstanceProfile: "ArgusServices-testS3"
      Tags:
      - Key: Name
        Value: !Sub "${APIName}-${EnvironmentName}-node01"
      - Key: SubModule
        Value: Ref! APIName
      - Key: Createdby
        Value: "asteam"
      - Key: Platform
        Value: "vanguard"
      - Key: Env
        Value: "poc"
      - Key: Scope
        Value: "as"
      UserData:
        Fn::Base64: !Sub |
          <powershell>
          New-Item -Path c:\temp -ItemType "directory" -Force
          powershell.exe -Command Read-S3Object -BucketName aws-codedeploy-us-east-2/latest -Key codedeploy-agent.msi -File c:\temp\codedeploy-agent.msi
          Start-Process -Wait -FilePath c:\temp\codedeploy-agent.msi -WindowStyle Hidden
          New-Item –Path "c:\BBCNews" –ItemType "directory" -Force
          [Environment]::SetEnvironmentVariable("AWS:CrazySQLServer","${SQLServer}","Machine")
          </powershell>
          <persist>true</persist>
  ASAPIProv:
    Type: AWS::EC2::Instance
    Condition: CreateEC2Provisioning
    Properties:
      ImageId: !Ref EC2ImageID
      KeyName: !Ref ASEC2Key
      InstanceType: t2.micro
      IamInstanceProfile: "ArgusServices-testS3"
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !Ref Subnet1
          GroupSet:
            - !Ref MySecurityGroup
      Tags:
      - Key: Name
        Value: !Sub "${APIName}-${EnvironmentName}-node01"
      - Key: SubModule
        Value: Ref! APIName
      - Key: Createdby
        Value: "asteam"
      - Key: Platform
        Value: "vanguard"
      - Key: Env
        Value: "poc"
      - Key: Scope
        Value: "as"
      UserData:
        Fn::Base64: !Sub |
          <powershell>
          New-Item -Path c:\temp -ItemType "directory" -Force
          powershell.exe -Command Read-S3Object -BucketName aws-codedeploy-us-east-2/latest -Key codedeploy-agent.msi -File c:\temp\codedeploy-agent.msi
          Start-Process -Wait -FilePath c:\temp\codedeploy-agent.msi -WindowStyle Hidden
          New-Item –Path "c:\CodeProvisioiningxyz" –ItemType "directory" -Force
          [Environment]::SetEnvironmentVariable("AWS:CrazySQLServer","${SQLServer}","Machine")
          </powershell>
          <persist>true</persist>
  ASAPIWorkSpace:
    Type: AWS::EC2::Instance
    Condition: CreateEC2Workspace
    Properties:
      ImageId: !Ref EC2ImageID
      KeyName: !Ref ASEC2Key
      InstanceType: t2.micro
      IamInstanceProfile: "ArgusServices-testS3"
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !Ref Subnet1
          GroupSet:
            - !Ref MySecurityGroup
      Tags:
      - Key: Name
        Value: !Sub "${APIName}-${EnvironmentName}-node01"
      - Key: SubModule
        Value: Ref! APIName
      - Key: Createdby
        Value: "asteam"
      - Key: Platform
        Value: "vanguard"
      - Key: Env
        Value: "poc"
      - Key: Scope
        Value: "as"
      UserData:
        Fn::Base64: !Sub |
          <powershell>
          New-Item -Path c:\temp -ItemType "directory" -Force
          powershell.exe -Command Read-S3Object -BucketName aws-codedeploy-us-east-2/latest -Key codedeploy-agent.msi -File c:\temp\codedeploy-agent.msi
          Start-Process -Wait -FilePath c:\temp\codedeploy-agent.msi -WindowStyle Hidden
          New-Item –Path "c:\CodeProvisioiningxyz" –ItemType "directory" -Force
          [Environment]::SetEnvironmentVariable("AWS:CrazySQLServer","${SQLServer}","Machine")
          </powershell>
          <persist>true</persist>
  ASAPIWorkSpaceReports:
    Type: AWS::EC2::Instance
    Condition: CreateEC2WorkspaceReports
    Properties:
      ImageId: !Ref EC2ImageID
      KeyName: !Ref ASEC2Key
      InstanceType: t2.micro
      IamInstanceProfile: "ArgusServices-testS3"
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !Ref Subnet1
          GroupSet:
            - !Ref MySecurityGroup
      Tags:
      - Key: Name
        Value: !Sub "${APIName}-${EnvironmentName}-node01"
      - Key: SubModule
        Value: Ref! APIName
      - Key: Createdby
        Value: "asteam"
      - Key: Platform
        Value: "vanguard"
      - Key: Env
        Value: "poc"
      - Key: Scope
        Value: "as"
      UserData:
        Fn::Base64: !Sub |
          <powershell>
          New-Item -Path c:\temp -ItemType "directory" -Force
          powershell.exe -Command Read-S3Object -BucketName aws-codedeploy-us-east-2/latest -Key codedeploy-agent.msi -File c:\temp\codedeploy-agent.msi
          Start-Process -Wait -FilePath c:\temp\codedeploy-agent.msi -WindowStyle Hidden
          New-Item –Path "c:\CodeProvisioiningxyz" –ItemType "directory" -Force
          [Environment]::SetEnvironmentVariable("AWS:CrazySQLServer","${SQLServer}","Machine")
          </powershell>
          <persist>true</persist>
Outputs:
  EC2node01URL:
    Condition: CreateEC2WorkspaceReports
    Description: End point of first API
    Value: !GetAtt ASAPIWorkSpaceReports.PublicDnsName
  EC2node01URL:
    Condition: CreateEC2Workspace
    Description: End point of first API
    Value: !GetAtt ASAPIWorkSpace.PublicDnsName
  EC2node01URL:
    Condition: CreateEC2Provisioning
    Description: End point of first API
    Value: !GetAtt ASAPIProv.PublicDnsName
  EC2node01URL:
    Condition: CreateEC2ModelOrganization
    Description: End point of first API
    Value: !GetAtt ASAPIModelOrg.PublicDnsName
  NODE01Output:
    Condition: CreateEC2WorkspaceReports
    Description: Model API1 node01
    Value: !Ref ASAPIWorkSpaceReports
    Export:
      Name: !Sub "${EnvironmentName}-${APIName}-ec2-node01"
  NODE02Output:
    Condition: CreateEC2Workspace
    Description: Model API1 node01
    Value: !Ref ASAPIWorkSpace
    Export:
      Name: !Sub "${EnvironmentName}-${APIName}-ec2-node001"
  NODE03Output:
    Condition: CreateEC2Provisioning
    Description: Model API1 node01
    Value: !Ref ASAPIProv
    Export:
      Name: !Sub "${EnvironmentName}-${APIName}-ec2-node01"
  NODE04Output:
    Condition: CreateEC2ModelOrganization
    Description: Model API1 node01
    Value: !Ref ASAPIModelOrg
    Export:
      Name: !Sub "${EnvironmentName}-${APIName}-ec2-node001"
