AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  EnvironmentName:
    Type: String
    Default: Dev
  APIName:
    Type: String
    Default: WorkspaceReports
  EC2Type:
    Type: String
    Description: EC2 instance type for Bastion
    Default: t2.medium
  VPC:
    Type: AWS::EC2::VPC::Id
    Default: vpc-7aec6412
  Subnet1:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-7709841f
  Subnet2:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-d9242194
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
    Default: sg-dc91b7b7
  EC2ImageID:
    Type: String
    Default: ami-d9ecdfbc
  KeyName:
    Type: String
    Default: altus-test-key
Conditions:
  CreateEC2ModelOrganization: !Equals [!Ref APIName, "ModelOrganization"]
  CreateEC2Provisioning: !Equals [!Ref APIName, "Provisioning"]
  CreateEC2Workspace: !Equals [!Ref APIName, "Workspace"]
  CreateEC2WorkspaceReports: !Equals [!Ref APIName, "WorkspaceReports"]
Resources:
  ASAPIModelOrg:
    Type: AWS::EC2::Instance
    Condition: CreateEC2ModelOrganization
    Properties:
      ImageId: !Ref EC2ImageID
      InstanceType: t2.micro
      IamInstanceProfile: "ArgusServices-testS3"
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !Ref Subnet1
          GroupSet:
            - !Ref MySecurityGroup
      Tags:
      - Key: Name
        Value: !Sub "${APIName}-${EnvironmentName}-node01"
      - Key: Createdby
        Value: "asteam"
  ASAPIProv:
    Type: AWS::EC2::Instance
    Condition: CreateEC2Provisioning
    Properties:
      ImageId: !Ref EC2ImageID
      KeyName: !Ref KeyName
      InstanceType: t2.micro
      IamInstanceProfile: "ArgusServices-testS3"
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !Ref Subnet1
          GroupSet:
            - !Ref MySecurityGroup
      Tags:
      - Key: Name
        Value: !Sub "${APIName}-${EnvironmentName}-node01"
      - Key: Createdby
        Value: "aseam"
  ASAPIWorkSpace:
    Type: AWS::EC2::Instance
    Condition: CreateEC2Workspace
    Properties:
      ImageId: !Ref EC2ImageID
      KeyName: !Ref KeyName
      InstanceType: t2.micro
      IamInstanceProfile: "ArgusServices-testS3"
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !Ref Subnet1
          GroupSet:
            - !Ref MySecurityGroup
      Tags:
      - Key: Name
        Value: !Sub "${APIName}-${EnvironmentName}-node01"
      - Key: Createdby
        Value: "asteam"
  ASAPIWorkSpaceReports:
    Type: AWS::EC2::Instance
    Condition: CreateEC2WorkspaceReports
    Properties:
      ImageId: !Ref EC2ImageID
      KeyName: !Ref KeyName
      InstanceType: t2.micro
      IamInstanceProfile: "ArgusServices-testS3"
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !Ref Subnet1
          GroupSet:
            - !Ref MySecurityGroup
      Tags:
      - Key: Name
        Value: !Sub "${APIName}-${EnvironmentName}-node01"
      - Key: Createdby
        Value: "aseam"
Outputs:
  EC2node01URL:
    Condition: CreateEC2WorkspaceReports
    Description: End point of first API
    Value: !GetAtt ASAPIWorkSpaceReports.PublicDnsName
  EC2node01URL:
    Condition: CreateEC2Workspace
    Description: End point of first API
    Value: !GetAtt ASAPIWorkSpace.PublicDnsName
  EC2node01URL:
    Condition: CreateEC2Provisioning
    Description: End point of first API
    Value: !GetAtt ASAPIProv.PublicDnsName
  EC2node01URL:
    Condition: CreateEC2ModelOrganization
    Description: End point of first API
    Value: !GetAtt ASAPIModelOrg.PublicDnsName
  NODE01Output:
    Condition: CreateEC2WorkspaceReports
    Description: Model API1 node01
    Value: !Ref ASAPIWorkSpaceReports
    Export:
      Name: !Sub "${EnvironmentName}-${APIName}-ec2-node01"
  NODE02Output:
    Condition: CreateEC2Workspace
    Description: Model API1 node01
    Value: !Ref ASAPIWorkSpace
    Export:
      Name: !Sub "${EnvironmentName}-${APIName}-ec2-node01"
  NODE03Output:
    Condition: CreateEC2Provisioning
    Description: Model API1 node01
    Value: !Ref ASAPIProv
    Export:
      Name: !Sub "${EnvironmentName}-${APIName}-ec2-node01"
  NODE04Output:
    Condition: CreateEC2ModelOrganization
    Description: Model API1 node01
    Value: !Ref ASAPIModelOrg
    Export:
      Name: !Sub "${EnvironmentName}-${APIName}-ec2-node01"
