AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  EnvironmentName:
    Type: String
    Default: UAT
Resources:
  ArgusServicesModelOrganizationAPI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://s3.us-east-2.amazonaws.com/cfscripts-altus-as/AS01/ec2instances.yaml"
      Parameters:
        EnvironmentName: !Sub ${EnvironmentName}
        APIName: ModelOrganization
  ArgusServicesProvisioningAPI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://s3.us-east-2.amazonaws.com/cfscripts-altus-as/AS01/ec2instances.yaml"
      Parameters:
        EnvironmentName: !Sub ${EnvironmentName}
        APIName: Provisioning
  ArgusServicesWorkspaceAPI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://s3.us-east-2.amazonaws.com/cfscripts-altus-as/AS01/ec2instances.yaml"
      Parameters:
        EnvironmentName: !Sub ${EnvironmentName}
        APIName: Workspace
  ArgusServicesWorkspaceReportsAPI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://s3.us-east-2.amazonaws.com/cfscripts-altus-as/AS01/ec2instances.yaml"
      Parameters:
        EnvironmentName: !Sub ${EnvironmentName}
        APIName: WorkspaceReports

