AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  VPC:
    Type: AWS::EC2::VPC::Id
    Default: vpc-ffea1784
  Subnet1:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-a09f53af
  Subnet2:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-f00a2acf
  SG1:
    Type: String
    Default: sg-9497fbe3
Resources:
  loadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: NLB01
      Scheme: internal
      Subnets:
      - Ref: Subnet1
      - Ref: Subnet2
      LoadBalancerAttributes:
      - Key: idle_timeout.timeout_seconds
        Value: '50'
      SecurityGroups:
      - Ref: SG1
      Tags:
      - Key: key
        Value: value
      - Key: key2
        Value: value2
