AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  VPC:
    Type: AWS::EC2::VPC::Id
    Default: vpc-ffea1784
  Subnet1:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-a09f53af
  Subnet2:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-f00a2acf
Resources:
  NLBDemoloadbalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: NLB01
      Scheme: internal
      Type: network
      Subnets:
      - Ref: Subnet1
      - Ref: Subnet2
      Tags:
      - Key: key
        Value: value
      - Key: key2
        Value: value2
  NLBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
      - Type: forward
        TargetGroupArn:
          Ref: NLBDemoTargetGroup
      LoadBalancerArn:
        Ref: NLBDemoloadbalancer
      Port: '80'
      Protocol: TCP
  NLBDemoTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckProtocol: TCP
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 3 
      Name: TG01
      Port: 80
      Protocol: TCP
      TargetGroupAttributes:
      - Key: deregistration_delay.timeout_seconds
        Value: '20'
      UnhealthyThresholdCount: 3
      VpcId:
        Ref: VPC

