param([string]$redisurl = "red", [string]$sqlurl = "sql", [string]$tokenkey = "tokenkey", [string]$awsregion = "ohio", [string]$s3bucket = "argus-dev", [string]$wso2 = "http://wso2", [string]$CalcSqs = "calc", [string]$AvuxSqs = "avux")
[Environment]::SetEnvironmentVariable("AWSRegion","$awsregion","Machine")
[Environment]::SetEnvironmentVariable("DataStoreRedisConnectionString","$redisurl","Machine")
[Environment]::SetEnvironmentVariable("ConnectionStrings:ProvisionDataStoreContext","$sqlurl","Machine")
[Environment]::SetEnvironmentVariable("RabbitMq.HostName","eagle.rmq.cloudamqp.com","Machine")
[Environment]::SetEnvironmentVariable("RabbitMq.Password","W02OQ_icpmti-rUckYwwIvLf25Y0mkHE","Machine")
[Environment]::SetEnvironmentVariable("RabbitMq.UserName","vmfjeeyz","Machine")
[Environment]::SetEnvironmentVariable("RabbitMq.Port","5671","Machine")
[Environment]::SetEnvironmentVariable("RabbitMq.VirtualHost","vmfjeeyz","Machine")
