param([string]$redisurl = "red", [string]$sqlurl = "sql", [string]$tokenkey = "tokenkey", [string]$awsregion = "ohio", [string]$s3bucket = "argus-dev", [string]$wso2 = "http://wso2", [string]$CalcSqs = "calc", [string]$AvuxSqs = "avux")
[Environment]::SetEnvironmentVariable("AWS:Region","$awsregion","Machine")
[Environment]::SetEnvironmentVariable("ConnectionStrings:DataStoreRedisConnectionString","$redisurl","Machine")
[Environment]::SetEnvironmentVariable("ConnectionStrings:WorkspaceRedisConnectionString","$redisurl","Machine")
[Environment]::SetEnvironmentVariable("Tokens:Key","$tokenkey","Machine")
[Environment]::SetEnvironmentVariable("ConnectionStrings:ProvisionDataStoreContext","$sqlurl","Machine")
